interval-seconds: 300
warnings:
  - time: 60
    message: "§7[§c!&7] Nettoyage des items dans &c60 &7secondes!"
  - time: 10
    message: "§7[§c!&7] Nettoyage des items dans &c10 &7secondes!"
done-message: "§7[§e?&7] {count} &aitems ont été supprimés."


messages:
    enabled: true

    # true = message à tout le serveur, false = seulement au joueur
    broadcast: true

    # message quand le joueur passe AFK
    now-afk: "&e{PLAYER} &7est maintenant &7[AFK]"

    # message quand le joueur revient
    no-longer-afk: "&e{PLAYER} &7n'est plus AFK"

  # Message de kick (codes couleurs avec &)
kick-message: "§7[§c!&7] Kick: AFK trop longtemps."

addLoreOnCreative: true
loreitem: "&7Remboursé par &b{staff}"
